/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq.tables.records;


import com.jiangtj.platform.system.jooq.tables.SystemRole;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemRoleRecord extends UpdatableRecordImpl<SystemRoleRecord> implements Record1<String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>system-db.system_role.key</code>.
     */
    public void setKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>system-db.system_role.key</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getKey() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SystemRole.SYSTEM_ROLE.KEY;
    }

    @Override
    public String component1() {
        return getKey();
    }

    @Override
    public String value1() {
        return getKey();
    }

    @Override
    public SystemRoleRecord value1(String value) {
        setKey(value);
        return this;
    }

    @Override
    public SystemRoleRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemRoleRecord
     */
    public SystemRoleRecord() {
        super(SystemRole.SYSTEM_ROLE);
    }

    /**
     * Create a detached, initialised SystemRoleRecord
     */
    public SystemRoleRecord(String key) {
        super(SystemRole.SYSTEM_ROLE);

        setKey(key);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SystemRoleRecord
     */
    public SystemRoleRecord(com.jiangtj.platform.system.jooq.tables.pojos.SystemRole value) {
        super(SystemRole.SYSTEM_ROLE);

        if (value != null) {
            setKey(value.key());
            resetChangedOnNotNull();
        }
    }
}
