/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq.tables.records;


import com.jiangtj.platform.system.jooq.tables.SystemKeyShare;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SystemKeyShareRecord extends UpdatableRecordImpl<SystemKeyShareRecord> implements Record3<String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jc_admin.system_key_share.kid</code>.
     */
    public void setKid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jc_admin.system_key_share.kid</code>.
     */
    @NotNull
    @Size(max = 256)
    public String getKid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jc_admin.system_key_share.jwk</code>.
     */
    public void setJwk(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jc_admin.system_key_share.jwk</code>.
     */
    @NotNull
    @Size(max = 256)
    public String getJwk() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jc_admin.system_key_share.publish_time</code>.
     */
    public void setPublishTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>jc_admin.system_key_share.publish_time</code>.
     */
    @NotNull
    public LocalDateTime getPublishTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SystemKeyShare.SYSTEM_KEY_SHARE.KID;
    }

    @Override
    public Field<String> field2() {
        return SystemKeyShare.SYSTEM_KEY_SHARE.JWK;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return SystemKeyShare.SYSTEM_KEY_SHARE.PUBLISH_TIME;
    }

    @Override
    public String component1() {
        return getKid();
    }

    @Override
    public String component2() {
        return getJwk();
    }

    @Override
    public LocalDateTime component3() {
        return getPublishTime();
    }

    @Override
    public String value1() {
        return getKid();
    }

    @Override
    public String value2() {
        return getJwk();
    }

    @Override
    public LocalDateTime value3() {
        return getPublishTime();
    }

    @Override
    public SystemKeyShareRecord value1(String value) {
        setKid(value);
        return this;
    }

    @Override
    public SystemKeyShareRecord value2(String value) {
        setJwk(value);
        return this;
    }

    @Override
    public SystemKeyShareRecord value3(LocalDateTime value) {
        setPublishTime(value);
        return this;
    }

    @Override
    public SystemKeyShareRecord values(String value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemKeyShareRecord
     */
    public SystemKeyShareRecord() {
        super(SystemKeyShare.SYSTEM_KEY_SHARE);
    }

    /**
     * Create a detached, initialised SystemKeyShareRecord
     */
    public SystemKeyShareRecord(String kid, String jwk, LocalDateTime publishTime) {
        super(SystemKeyShare.SYSTEM_KEY_SHARE);

        setKid(kid);
        setJwk(jwk);
        setPublishTime(publishTime);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SystemKeyShareRecord
     */
    public SystemKeyShareRecord(com.jiangtj.platform.system.jooq.tables.pojos.SystemKeyShare value) {
        super(SystemKeyShare.SYSTEM_KEY_SHARE);

        if (value != null) {
            setKid(value.kid());
            setJwk(value.jwk());
            setPublishTime(value.publishTime());
            resetChangedOnNotNull();
        }
    }
}
