/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq.tables.records;


import com.jiangtj.platform.system.jooq.tables.SystemUserRole;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SystemUserRoleRecord extends UpdatableRecordImpl<SystemUserRoleRecord> implements Record2<Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>jc_admin.system_user_role.user_id</code>.
     */
    public void setUserId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jc_admin.system_user_role.user_id</code>.
     */
    @NotNull
    public Long getUserId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jc_admin.system_user_role.role</code>.
     */
    public void setRole(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jc_admin.system_user_role.role</code>.
     */
    @NotNull
    @Size(max = 32)
    public String getRole() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SystemUserRole.SYSTEM_USER_ROLE.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return SystemUserRole.SYSTEM_USER_ROLE.ROLE;
    }

    @Override
    public Long component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getRole();
    }

    @Override
    public Long value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getRole();
    }

    @Override
    public SystemUserRoleRecord value1(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public SystemUserRoleRecord value2(String value) {
        setRole(value);
        return this;
    }

    @Override
    public SystemUserRoleRecord values(Long value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SystemUserRoleRecord
     */
    public SystemUserRoleRecord() {
        super(SystemUserRole.SYSTEM_USER_ROLE);
    }

    /**
     * Create a detached, initialised SystemUserRoleRecord
     */
    public SystemUserRoleRecord(Long userId, String role) {
        super(SystemUserRole.SYSTEM_USER_ROLE);

        setUserId(userId);
        setRole(role);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SystemUserRoleRecord
     */
    public SystemUserRoleRecord(com.jiangtj.platform.system.jooq.tables.pojos.SystemUserRole value) {
        super(SystemUserRole.SYSTEM_USER_ROLE);

        if (value != null) {
            setUserId(value.userId());
            setRole(value.role());
            resetChangedOnNotNull();
        }
    }
}
