# Use root/example as user/password credentials
version: '3.1'

services:

  jc_admin:
    container_name: jc-admin-db
    image: m.daocloud.io/docker.io/library/mysql:9.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jc_admin
      MYSQL_ROOT_PASSWORD: bressdfthytdbttgy
      CHARACTER_SET_SERVER: utf8mb4
      COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3311:3306"

  polaris:
    container_name: polaris-standalone
    image: polarismesh/polaris-standalone:v1.17.2
    restart: unless-stopped
    ports:
      - "15010:15010"
      - "8101:8101"
      - "8100:8100"
      - "18080:8080"
      - "18090:8090"
      - "18091:8091"
      - "18093:8093"
      - "18761:8761"
      - "19090:9090"