spring:
  cloud:
    gateway:
      routes:
        - id: system-login
          uri: lb://system-server
          predicates:
            - Path=/login
          filters:
            - SaveUserToSession
        - id: system
          uri: lb://system-server
          predicates:
            - Path=/**
          filters:
            - AddToken
#        - id: sba
#          # lb: Ribbon
#          # uri: lb://sba-server
#          uri: http://localhost:9998
#          predicates:
#            - Path=/sba/**
#          filters:
#            # Strip first path，such base
#            # - StripPrefix=1
#            - RewritePath=/sba/,/
#          metadata:
#            cors:
#              allowedOrigins: '*'
#              allowedMethods:
#                - GET
#                - POST
#              allowedHeaders: '*'
#              maxAge: 30