/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq;


import com.jiangtj.platform.system.jooq.tables.*;
import com.jiangtj.platform.system.jooq.tables.records.*;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * system-db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("KEY_DATABASECHANGELOGLOCK_PRIMARY"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<SystemOperateRecordRecord> KEY_SYSTEM_OPERATE_RECORD_PRIMARY = Internal.createUniqueKey(SystemOperateRecord.SYSTEM_OPERATE_RECORD, DSL.name("KEY_system_operate_record_PRIMARY"), new TableField[] { SystemOperateRecord.SYSTEM_OPERATE_RECORD.ID }, true);
    public static final UniqueKey<SystemRoleRecord> KEY_SYSTEM_ROLE_PRIMARY = Internal.createUniqueKey(SystemRole.SYSTEM_ROLE, DSL.name("KEY_system_role_PRIMARY"), new TableField[] { SystemRole.SYSTEM_ROLE.KEY }, true);
    public static final UniqueKey<SystemRoleCreatorRecord> KEY_SYSTEM_ROLE_CREATOR_PRIMARY = Internal.createUniqueKey(SystemRoleCreator.SYSTEM_ROLE_CREATOR, DSL.name("KEY_system_role_creator_PRIMARY"), new TableField[] { SystemRoleCreator.SYSTEM_ROLE_CREATOR.ROLE_KEY, SystemRoleCreator.SYSTEM_ROLE_CREATOR.CREATOR }, true);
    public static final UniqueKey<SystemUserRecord> KEY_SYSTEM_USER_PRIMARY = Internal.createUniqueKey(SystemUser.SYSTEM_USER, DSL.name("KEY_system_user_PRIMARY"), new TableField[] { SystemUser.SYSTEM_USER.ID }, true);
    public static final UniqueKey<SystemUserRoleRecord> KEY_SYSTEM_USER_ROLE_PRIMARY = Internal.createUniqueKey(SystemUserRole.SYSTEM_USER_ROLE, DSL.name("KEY_system_user_role_PRIMARY"), new TableField[] { SystemUserRole.SYSTEM_USER_ROLE.USER_ID, SystemUserRole.SYSTEM_USER_ROLE.ROLE }, true);
}
