/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq;


import com.jiangtj.platform.system.jooq.tables.*;


/**
 * Convenience access to all tables in system-db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>system-db.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>system-db.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>system-db.system_operate_record</code>.
     */
    public static final SystemOperateRecord SYSTEM_OPERATE_RECORD = SystemOperateRecord.SYSTEM_OPERATE_RECORD;

    /**
     * The table <code>system-db.system_role</code>.
     */
    public static final SystemRole SYSTEM_ROLE = SystemRole.SYSTEM_ROLE;

    /**
     * The table <code>system-db.system_role_creator</code>.
     */
    public static final SystemRoleCreator SYSTEM_ROLE_CREATOR = SystemRoleCreator.SYSTEM_ROLE_CREATOR;

    /**
     * The table <code>system-db.system_user</code>.
     */
    public static final SystemUser SYSTEM_USER = SystemUser.SYSTEM_USER;

    /**
     * The table <code>system-db.system_user_role</code>.
     */
    public static final SystemUserRole SYSTEM_USER_ROLE = SystemUserRole.SYSTEM_USER_ROLE;
}
