/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq;


import com.jiangtj.platform.system.jooq.tables.Databasechangelog;
import com.jiangtj.platform.system.jooq.tables.Databasechangeloglock;
import com.jiangtj.platform.system.jooq.tables.SystemKeyShare;
import com.jiangtj.platform.system.jooq.tables.SystemOperateRecord;
import com.jiangtj.platform.system.jooq.tables.SystemUser;
import com.jiangtj.platform.system.jooq.tables.SystemUserRole;


/**
 * Convenience access to all tables in jc_admin.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>jc_admin.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>jc_admin.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>jc_admin.system_key_share</code>.
     */
    public static final SystemKeyShare SYSTEM_KEY_SHARE = SystemKeyShare.SYSTEM_KEY_SHARE;

    /**
     * The table <code>jc_admin.system_operate_record</code>.
     */
    public static final SystemOperateRecord SYSTEM_OPERATE_RECORD = SystemOperateRecord.SYSTEM_OPERATE_RECORD;

    /**
     * The table <code>jc_admin.system_user</code>.
     */
    public static final SystemUser SYSTEM_USER = SystemUser.SYSTEM_USER;

    /**
     * The table <code>jc_admin.system_user_role</code>.
     */
    public static final SystemUserRole SYSTEM_USER_ROLE = SystemUserRole.SYSTEM_USER_ROLE;
}
