/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq.tables;


import com.jiangtj.platform.system.jooq.Keys;
import com.jiangtj.platform.system.jooq.SystemDb;
import com.jiangtj.platform.system.jooq.tables.records.SystemRoleRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemRole extends TableImpl<SystemRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>system-db.system_role</code>
     */
    public static final SystemRole SYSTEM_ROLE = new SystemRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemRoleRecord> getRecordType() {
        return SystemRoleRecord.class;
    }

    /**
     * The column <code>system-db.system_role.key</code>.
     */
    public final TableField<SystemRoleRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    private SystemRole(Name alias, Table<SystemRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemRole(Name alias, Table<SystemRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>system-db.system_role</code> table reference
     */
    public SystemRole(String alias) {
        this(DSL.name(alias), SYSTEM_ROLE);
    }

    /**
     * Create an aliased <code>system-db.system_role</code> table reference
     */
    public SystemRole(Name alias) {
        this(alias, SYSTEM_ROLE);
    }

    /**
     * Create a <code>system-db.system_role</code> table reference
     */
    public SystemRole() {
        this(DSL.name("system_role"), null);
    }

    public <O extends Record> SystemRole(Table<O> child, ForeignKey<O, SystemRoleRecord> key) {
        super(child, key, SYSTEM_ROLE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : SystemDb.SYSTEM_DB;
    }

    @Override
    public UniqueKey<SystemRoleRecord> getPrimaryKey() {
        return Keys.KEY_SYSTEM_ROLE_PRIMARY;
    }

    @Override
    public SystemRole as(String alias) {
        return new SystemRole(DSL.name(alias), this);
    }

    @Override
    public SystemRole as(Name alias) {
        return new SystemRole(alias, this);
    }

    @Override
    public SystemRole as(Table<?> alias) {
        return new SystemRole(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemRole rename(String name) {
        return new SystemRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemRole rename(Name name) {
        return new SystemRole(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemRole rename(Table<?> name) {
        return new SystemRole(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function1<? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function1<? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
