/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.sql.jooq.jooq;


import com.jiangtj.platform.sql.jooq.jooq.tables.*;


/**
 * Convenience access to all tables in system-db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>system-db.DATABASECHANGELOG</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>system-db.DATABASECHANGELOGLOCK</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>system-db.system_operate_record</code>.
     */
    public static final SystemOperateRecord SYSTEM_OPERATE_RECORD = SystemOperateRecord.SYSTEM_OPERATE_RECORD;

    /**
     * The table <code>system-db.system_user</code>.
     */
    public static final SystemUser SYSTEM_USER = SystemUser.SYSTEM_USER;

    /**
     * The table <code>system-db.system_user_role</code>.
     */
    public static final SystemUserRole SYSTEM_USER_ROLE = SystemUserRole.SYSTEM_USER_ROLE;
}
