/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record SystemRoleCreator(
    String roleKey,
    String creator,
    String alias,
    String name,
    Byte autoCreate
) implements Serializable {

    private static final long serialVersionUID = 1L;


    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SystemRoleCreator other = (SystemRoleCreator) obj;
        if (this.roleKey == null) {
            if (other.roleKey != null)
                return false;
        }
        else if (!this.roleKey.equals(other.roleKey))
            return false;
        if (this.creator == null) {
            if (other.creator != null)
                return false;
        }
        else if (!this.creator.equals(other.creator))
            return false;
        if (this.alias == null) {
            if (other.alias != null)
                return false;
        }
        else if (!this.alias.equals(other.alias))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.autoCreate == null) {
            if (other.autoCreate != null)
                return false;
        }
        else if (!this.autoCreate.equals(other.autoCreate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.roleKey == null) ? 0 : this.roleKey.hashCode());
        result = prime * result + ((this.creator == null) ? 0 : this.creator.hashCode());
        result = prime * result + ((this.alias == null) ? 0 : this.alias.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.autoCreate == null) ? 0 : this.autoCreate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemRoleCreator (");

        sb.append(roleKey);
        sb.append(", ").append(creator);
        sb.append(", ").append(alias);
        sb.append(", ").append(name);
        sb.append(", ").append(autoCreate);

        sb.append(")");
        return sb.toString();
    }
}
