/*
 * This file is generated by jOOQ.
 */
package com.jiangtj.platform.system.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public record SystemKeyShare(
    String kid,
    String jwk,
    LocalDateTime publishTime,
    LocalDateTime readTime
) implements Serializable {

    private static final long serialVersionUID = 1L;


    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SystemKeyShare other = (SystemKeyShare) obj;
        if (this.kid == null) {
            if (other.kid != null)
                return false;
        }
        else if (!this.kid.equals(other.kid))
            return false;
        if (this.jwk == null) {
            if (other.jwk != null)
                return false;
        }
        else if (!this.jwk.equals(other.jwk))
            return false;
        if (this.publishTime == null) {
            if (other.publishTime != null)
                return false;
        }
        else if (!this.publishTime.equals(other.publishTime))
            return false;
        if (this.readTime == null) {
            if (other.readTime != null)
                return false;
        }
        else if (!this.readTime.equals(other.readTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.kid == null) ? 0 : this.kid.hashCode());
        result = prime * result + ((this.jwk == null) ? 0 : this.jwk.hashCode());
        result = prime * result + ((this.publishTime == null) ? 0 : this.publishTime.hashCode());
        result = prime * result + ((this.readTime == null) ? 0 : this.readTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SystemKeyShare (");

        sb.append(kid);
        sb.append(", ").append(jwk);
        sb.append(", ").append(publishTime);
        sb.append(", ").append(readTime);

        sb.append(")");
        return sb.toString();
    }
}
