spring: 
  cloud: 
    gateway: 
      routes: 
        - id: system
          uri: lb://system-server
          predicates: 
            - Path=/system/**
          filters: 
            - AddToken
            - StripPrefix=1
        - id: dashboard
          uri: http://127.0.0.1:5173/
          predicates: 
            - Path=/**
