# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker Push

on:
  push:
    branches:
      - master
      - docker
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: m.daocloud.io/docker.io/library/mysql:9.0
        env:
          MYSQL_DATABASE: jc_admin
          MYSQL_ROOT_PASSWORD: 123456
          CHARACTER_SET_SERVER: utf8mb4
          COLLATION_SERVER: utf8mb4_unicode_ci
        ports:
          - 3311:3306
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn test

  docker_push_system:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-build-and-push
        with:
          module-name: system-server
          password: ${{ secrets.GITHUB_TOKEN }}

  docker_push_core:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-build-and-push
        with:
          module-name: core-server
          password: ${{ secrets.GITHUB_TOKEN }}