
name: Java CI with Maven Build

on:
  workflow_dispatch:
    inputs:
      profiles:
        description: 'config spring.profiles.active'
        default: 'default'
        required: false
        type: string
  workflow_call:
    inputs:
      profiles:
        description: 'config spring.profiles.active'
        default: 'default'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_DATABASE: system-db
          MYSQL_ROOT_PASSWORD: 123456
          CHARACTER_SET_SERVER: utf8mb4
          COLLATION_SERVER: utf8mb4_unicode_ci
        ports:
          - 3311:3306

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn package -Dspring.profiles.active=${{ inputs.profiles }}

      - name: Archive jar results
        uses: actions/upload-artifact@v3
        with:
          name: results-jar
          path: '*/target/*.jar'
